---
title: "Price effect"
format: html
editor: visual
---

# How does income impact death rate?

## Load libraries and data

### Load libraries

```{r}
#| message: false
library(tidyverse)
library(here)
```

### Load data

```{r}
#| message: false
meta_data <- read_csv("data/med_data_tidy.csv")
```

## Preparing the metadata for analysis

```{r}
clean_data <- meta_data |>
  select(age, death, sex, diag_group, diag_class, income) |>
  mutate(income = gsub("\\$", "", income)) |>
  na.omit()

clean_data
```

### Cleaning the income column and adding new column

```{r}
clean_data <- clean_data |>
    mutate(income_num = case_when(income == "under 11k" ~ 11,
    income == "11-25k" ~ 18,
    income == "25-50k" ~ 37.5,
    income == ">50k" ~ 50))

clean_data
```

## Distribution plot

```{r}
income_plot <- ggplot(data = clean_data) +
  geom_bar(aes(x = income,
               fill = sex,), 
           position = "dodge") +
  labs(title="Distribution of income and sex in dataset")
  
income_plot
```

## Making the regression line

### Income vs diagnosis class

```{r}
income_vs_class <- clean_data |>
  lm(income_num ~  diag_class, data = _)
```

```{r}
income_vs_class |>
  summary()
```

```{r}
income_vs_class |>
  pluck("coefficients")
```

### Income vs class and death

```{r}
income_vs_class_death <- clean_data |>
  lm(income_num ~  diag_class + death, data = _)
```

```{r}
income_vs_class_death |>
  summary()
```

### Income vs class, death and age

```{r}
income_vs_everything <- clean_data |>
  lm(income_num ~  diag_class + death + age, data = _)
```

```{r}
income_vs_everything |>
  summary()
```

## Income vs. death

```{r}
incomedeath <- clean_data |>
  group_by(income) |>
  group_map(~ lm(income_num ~ death, data = .x))

names(models) <- unique(clean_data$income_class)

summaries <- models |> map(summary)
summaries

```

```{r}
$`under 11k`
<full summary here>

$`11-25k`
<full summary here>

$`25-50k`
<full summary here>

$`>50k`
<full summary here>

```

## Plots

```{r}
pl1 <- clean_data |>
  ggplot(mapping = aes(x = income_class,
                       y = death,
                       colour = sex)) +
  geom_point() + 
  geom_smooth(method = "lm")
  
pl1
```
