---
title: "Price effect"
format: html
editor: visual
---

# How does income impact death rate?

## Load libraries and data

### Load libraries

```{r}
#| message: false
library(tidyverse)
library(here)
```

### Load data

```{r}
#| message: false
meta_data <- read_csv("../data/med_data_tidy.csv")
```

## Preparing the data for analysis

```{r}
clean_data <- meta_data |>
  select(age, death, sex, diag_group, diag_class, income) |>
  mutate(income = gsub("\\$", "", income)) |> #To remove $ from the data
  na.omit()

clean_data
```

### Cleaning the income column and adding new column

```{r}
clean_data <- clean_data |>
  mutate(
    income_class = case_when(income == "under 11k" ~ "income very poor",
      income == "11-25k"    ~ "income poor",
      income == "25-50k"    ~ "income medium",
      income == ">50k"      ~ "income wealthy"
    ),
    income_num = case_when(income == "under 11k" ~ 11,
      income == "11-25k"    ~ 18,
      income == "25-50k"    ~ 37.5,
      income == ">50k"      ~ 50))

clean_data
```

## Distribution plot

```{r}
income_plot <- ggplot(data = clean_data) +
  geom_bar(aes(x = income,
               fill = sex,), 
           position = "dodge") +
  labs(title="Distribution of income and sex in dataset")
  
income_plot
```

## Making the regression line

### Income vs diagnosis class

```{r}
income_vs_class <- clean_data |>
  lm(income_num ~  diag_class, data = _)
```

```{r}
income_vs_class |>
  summary()
```

```{r}
income_vs_class |>
  pluck("coefficients")
```

### Income vs class and death

```{r}
income_vs_class_death <- clean_data |>
  lm(income_num ~  diag_class + death, data = _)
```

```{r}
income_vs_class_death |>
  summary()
```

### Income vs class, death and age

```{r}
income_vs_everything <- clean_data |>
  lm(income_num ~  diag_class + death + age, data = _)
```

```{r}
income_vs_everything |>
  summary()
```

## Income vs. death

```{r}
incomedeath <- clean_data |>
  group_by(income) |>
  group_map(~ lm(income_num ~ death, data = .x))

names(incomedeath) <- unique(clean_data$income_class)

summaries <- incomedeath |> map(summary)
summaries

```

### Making models

```{r}
income_death_model <- lm(death ~ income_num, data = clean_data)
income_death_model |> summary()

```

```{r}
model_class <- lm(death ~ income_class, data = clean_data)
summary(model_class)

```

```{r}
glm(death ~ income_num, data = clean_data, family = binomial)

```

```{r}
clean_data
```

```{r}
med_income_verylow <- clean_data |> 
  filter(income_num == 11)

med_income_verylow_model <- lm(death ~ income_num, data = med_income_verylow)
med_income_verylow_model

```

```{r}
med_income_low <- clean_data |> 
  filter(income_num == 18)

med_income_low_model <- lm(death ~ income_num, data = med_income_low)
med_income_low_model

```

```{r}
med_income_medium <- clean_data |> 
  filter(income_num == 37.5)

med_income_medium_model <- lm(death ~ income_num, data = med_income_medium)
med_income_medium_model

```

```{r}
med_income_high <- clean_data |> 
  filter(income_num == 50)

med_income_high_model <- lm(death ~ income_num, data = med_income_high)
med_income_high_model

```

```{r}
df_med_income_models <- tibble(
  group = c("Very low income", 
            "Low income", 
            "Medium income", 
            "High income"),
  
  model = list(
    med_income_verylow_model,
    med_income_low_model,
    med_income_medium_model,
    med_income_high_model))
df_med_income_models
```

```{r}
df_income <- clean_data |>
  mutate(
    verypoor = case_when(income_class == "income very poor" ~ 1, .default = 0),
    poor     = case_when(income_class == "income poor" ~ 1, .default = 0),
    middle   = case_when(income_class == "income medium" ~ 1, .default = 0),
    wealthy  = case_when(income_class == "income wealthy" ~ 1, .default = 0))

```

```{r}
model_verypoor <- lm(death ~ verypoor, data = df_income)
model_poor     <- lm(death ~ poor, data = df_income)
model_middle   <- lm(death ~ middle, data = df_income)
model_wealthy  <- lm(death ~ wealthy, data = df_income)

df_income
```

```{r}
df_income_stat_models <- tibble(
  group = c("Income very low", "Income low", "Income medium", "Income wealthy"),
  model  = list(model_verypoor, model_poor, model_middle, model_wealthy))


```

```{r}
df_income_models <- df_income_stat_models |>
  write_rds(here("data/models/income.RDS"))

```

## Plots
