---
title: "Sex analysis"
format: html
---

# Load packages

```{r}
library(dplyr)
library(ggplot2)
library(tibble)
library(here)
```

# Load data

```{r}
df <- read.csv(here("data", "med_data_tidy.csv"))
df
```

# Create male_binary and female_binary.

```{r}
df <- df |>
mutate(male_binary = ifelse(sex == "male", 1, 0),
       female_binary = ifelse(sex == "female", 1, 0)
)
head(df[, c("sex", "male_binary", "female_binary")])

```

# create linear model for both sexes

```{r}
female_model <- lm(death ~ female_binary, data = df)
male_model <-   lm(death ~ male_binary, data = df)

model_df <- tibble(
group = c("female", "male"),
model = list(female_model, male_model)
)

model_df

```

# save to sex.RDS

```{r}
saveRDS(model_df, here("data/models/sex.RDS"))

readRDS(here("data", "models", "sex.RDS"))
```

## visualizations

# proportion of death for both sex

```{r}
df_sex_death <- df |>
  group_by(sex) |>
  summarise(
    death_rate = mean(death, na.rm = TRUE)
  )

deathrate_sex <- ggplot(df_sex_death, aes(x = sex, y = death_rate)) +
  geom_col(fill = "red",alpha=0.7) +
  labs(
    title = "Death Rate by Sex",
    x = "Sex",
    y = "Proportion Dead"
  )
deathrate_sex
```

```{r}
ggsave(filename=here("results/plots/Death_rate_sex.png"),
       plot=deathrate_sex,
       height = 5,
       width=8)
```

```{r}
ggplot(df, aes(x = sex, fill = factor(death))) +
  geom_bar(position = "dodge") +
  labs(
    title = "Alive vs Dead by Sex",
    x = "Sex",
    fill = "Death (1 = Dead)"
  )

```

```{r}
agesex_comparison <- ggplot(df, aes(x = age, fill = sex)) +
  geom_histogram(alpha = 0.6, position = "identity", bins = 30) +
  labs(
    title = "Age Distribution by Sex",
    x = "Age",
    y = "Count"
  )
agesex_comparison
```

```{r}
ggsave(filename=here("results/plots/Sex_age_distribution.png"),
       plot=agesex_comparison,
       height = 5,
       width=8)
```

```{r}
#models without age 
female_no_age <- lm(death ~ female_binary, data = df)
male_no_age   <- lm(death ~ male_binary, data = df)

# Models WITH age
female_with_age <- lm(death ~ female_binary + age, data = df)
male_with_age   <- lm(death ~ male_binary + age, data = df)

```

```{r}
extract_p <- function(model, variable){
  summary(model)$coefficients[variable, "Pr(>|t|)"]
}
```

```{r}
pvals <- tibble(
  sex = c("female", "female", "male", "male"),
  model = c("No age", "With age", "No age", "With age"),
  p_value = c(
    extract_p(female_no_age, "female_binary"),
    extract_p(female_with_age, "female_binary"),
    extract_p(male_no_age, "male_binary"),
    extract_p(male_with_age, "male_binary")
  )
)
pvals
```
