---
title: "integration"
format: html
---

```{r}
library(here)
library(tidyverse)
library(broom)
library(patchwork)
source(here("R/99_functions.R"))
```

## Loading the linear models from previous analysis

```{r}
income <- read_rds(here("data/models/income.RDS"))
race <- read_rds(here("data/models/race.RDS"))
sex <- read_rds(here("data/models/sex.RDS"))
edu <- read_rds(here("data/models/edu.RDS"))
age <- read_rds(here("data/models/age.RDS"))
diagnosis <- read_rds(here("data/models/diagnosis.RDS"))
```

```{r}
all_models <- bind_rows(income,race,sex,age,edu, diagnosis)
all_models
```

```{r}
all_models <- all_models |> mutate(
  nested_stats = map(.x=model,
                     .f= get_model_stats))
all_models
```

```{r}
all_models <- all_models |>
  unnest(nested_stats) |> 
  select(group,slope_est, slope_p, everything(),-model)

```

```{r}
all_models |> arrange(slope_p)
```

```{r}
all_models |> write_rds(here("data/compared_models.RDS"))
```

```{r}
p_accept <- all_models |> mutate(Significant = slope_p < 0.05) |>
  arrange(R_squared, slope_p)

p1 <- ggplot(p_accept, aes(x = group, y = R_squared, color = Significant)) +
  
  geom_point() +
  
  scale_color_manual(values = c("FALSE" = "black", "TRUE" = "red")) +
  
  labs(title = "Model R-squared values",        
    center =TRUE) +
    
  xlab("Model") + ylab("R-squared") +
  
  theme(axis.text.x = element_text(angle = 45, hjust = 1), legend.position   = "bottom")



p2 <- ggplot(p_accept, aes(x = group, y = slope_p, color = Significant)) +
  
  geom_point() +
  
  scale_color_manual(values = c("FALSE" = "black", "TRUE" = "red")) +
  
  labs(title = "Model slope p-values",        
    center =TRUE) +
    
  xlab("Model") + ylab("P-values") +
  
  theme(axis.text.x = element_text(angle = 45, hjust = 1), legend.position   = "bottom")



p1 + p2
```

### Sorted after p-value significant

```{r}
p_accept <- all_models |>
  mutate(Significant = slope_p < 0.05) |>
  arrange(desc(Significant), slope_p, slope_est) |>
  mutate(group = factor(group, levels = group))

p1 <- ggplot(p_accept, aes(x = group, y = slope_est, color = Significant)) +
  geom_point() +
  geom_errorbar(aes(ymin = slope_est - slope_std * 2,
                ymax = slope_est + slope_std * 2)) +
  scale_color_manual(
  values = c("FALSE" = "black", "TRUE" = "red"),
  labels = c("FALSE" = "Not significant", "TRUE" = "Is significant"),
  name = "") +  labs(title = "Model slope value estimates") +
  xlab("Feature") + 
  ylab("slope estimate") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1),
        legend.position = "bottom")


p2 <- ggplot(p_accept, aes(x = group, y = slope_p, color = Significant)) +
  geom_point() +
  scale_color_manual(
  values = c("FALSE" = "black", "TRUE" = "red"),
  labels = c("FALSE" = "Not significant", "TRUE" = "Is significant"),
  name = "") +
  labs(title = "Model slope p-values") +
  xlab("Feature") + 
  ylab("P-values") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1),
        legend.position = "bottom")

p1 + p2
```

```{r}
ggsave(filename = "../results/comparison.png",
  plot = p1 / p2,
  height = 10, width = 12)

```
