---
title: "Prosessing"
format: html
---

### Importing Packages

```{r}
#| message: false
library(tidyverse)
library(here)
library(readr)
```

### Medicine Equality in Education

```{r}
med_edu <- read_csv(here("data/med_data_tidy.csv"))
med_edu
```

Getting an overview of the amount of years of education shows that 8-15 years is the most common and will heavily sceew the coming analysis.

```{r}
med_edu |> ggplot(mapping = aes(x = edu)) + 
  geom_bar() + 
  labs(title = "Education frequency",        
    center =TRUE) +
  xlab("Years of education") + ylab("People")

```

If we group the education by years of 3, we then get the following table:

```{r}
med_edu_grouped <- med_edu |> 
  mutate(edu = case_when(0 <= edu & edu < 3 ~ "(0-3]",
                         3 <= edu & edu < 6 ~ "(3-6]",
                         6 <= edu & edu < 9 ~ "(6-9]",
                         9 <= edu & edu < 12 ~ "(9-12]",
                         12 <= edu & edu < 15 ~ "(12-15]",
                         15 <= edu & edu < 18 ~ "(15-18]",
                         18 <= edu & edu < 21 ~ "(18-21]",
                         21 <= edu & edu < 24 ~ "(21-24]",
                         24 <= edu & edu < 27 ~ "(24-27]",
                         27 <= edu & edu < 30 ~ "(27-30]"), 
  edu = factor(edu, levels=c("(0-3]", "(3-6]","(6-9]","(9-12]","(12-15]","(15-18]","(18-21]","(21-24]","(24-27]","(27-30]")))

med_edu_grouped |> group_by(edu) |> summarize(n = n())
```

```{r}
med_edu_grouped |>
  filter(!is.na(edu)) |>
  ggplot(aes(x = edu, y = death)) +
  stat_summary(fun = mean, geom = "point", size = 3) +
  stat_summary(fun = mean, geom = "line", group = 1)

```

```{r}
edu_death_model <- lm(death ~ edu, data = med_edu)
edu_death_model |> summary()
```

```{r}
med_edu_low <- med_edu_grouped |> 
  filter(edu == "(0-3]" | edu == "(3-6]" | edu == "(6-9]")

med_edu_low_model <- lm(death ~ edu, data = med_edu_low)
med_edu_low_model
```

```{r}
med_edu_medium <- med_edu_grouped |> 
  filter(edu == "(9-12]" | edu == "(12-15]" | edu == "(15-18]")

med_edu_medium_model <- lm(death ~ edu, data = med_edu_medium)
med_edu_medium_model
```

```{r}
med_edu_high <- med_edu_grouped |> 
  filter(edu == "(18-21]" | edu == "(21-24]" | edu == "(24-27]")

med_edu_high_model <- lm(death ~ edu, data = med_edu_high)
med_edu_high_model
```

```{r}
df_med_edu_models <- tibble(edu_interval = c("low", "medium", "high"),
                            model = list(med_edu_low_model, 
                                      med_edu_medium_model, 
                                      med_edu_high_model))

df_med_edu_models
```
